### ISSUE TITLE
Python 3: Bytes prefix

### ISSUE THREAD

**Issue by tidenhub** [jaraco/xlsxcessive#1]
Hello,
we are using xlsxcessive 0.4.1. It works just fine with Python 2.7 but in Python 3.6 all our cells have the b prefix.
If we remove the encoding of string values in @value.setter in Cell of worksheet.py, the problem is fixed.

![image1](https://user-images.githubusercontent.com/7394024/100611063-01a54100-3311-11eb-8b00-2f0028523f5d.png)

**Comment by jaraco** [comment]
Thanks for the report. Have a peek at v1.1.1 and report back if that doesn't do the trick.
